In [1]:
import numpy as np
# Set the maximum number of columns to display
np.set_printoptions(threshold=np.inf, linewidth=np.inf)

In [2]:
import numpy as np
def normalizer(data):
    return (data - np.mean(data,axis=0)) / (np.max(data, axis=0) - np.min(data, axis=0))




In [3]:
from sklearn.datasets import load_iris
import numpy as np
# Load the Iris dataset
iris = load_iris()

# Access the features (X) and target (y) data
X = iris.data
y = iris.target




In [4]:
# Importing a dataset with high number of features
from sklearn.datasets import fetch_california_housing

# Load the California Housing dataset
california_housing = fetch_california_housing()

# Access the features and target
X = california_housing.data  # Features
y = california_housing.target  # Target variable (median house value)

X = normalizer(X)


In [5]:
dir(california_housing)


['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [6]:
california_housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [7]:
X

array([[ 3.07204659e-01,  2.42363011e-01,  1.10243504e-02, -2.16004820e-03, -3.09279056e-02, -4.14520037e-04,  2.38909518e-01, -2.64969676e-01],
       [ 3.05563302e-01, -1.49793852e-01,  5.73600236e-03, -3.69944637e-03,  2.73416647e-02, -7.73202648e-04,  2.36784120e-01, -2.63973660e-01],
       [ 2.33564295e-01,  4.58049286e-01,  2.02685121e-02, -6.88601440e-04, -2.60510873e-02, -2.15987777e-04,  2.35721420e-01, -2.65965691e-01],
       [ 1.22234797e-01,  4.58049286e-01,  2.75303963e-03, -7.00072793e-04, -2.43133704e-02, -4.20644372e-04,  2.35721420e-01, -2.66961707e-01],
       [-1.68763210e-03,  4.58049286e-01,  6.04590800e-03, -4.62274759e-04, -2.41171766e-02, -7.15563030e-04,  2.35721420e-01, -2.66961707e-01],
       [ 1.14570142e-02,  4.58049286e-01, -4.73080828e-03,  2.06080832e-04, -2.83773857e-02, -7.49016624e-04,  2.35721420e-01, -2.66961707e-01],
       [-1.45909024e-02,  4.58049286e-01, -3.52391023e-03, -4.30770599e-03, -9.29052788e-03, -7.58264431e-04,  2.34658721e-01, -2.

In [8]:
import pandas as pd
pd.set_option('display.max_columns', None)  # Show all columns

In [9]:
df = pd.DataFrame(X, columns = california_housing.feature_names)

In [10]:
df.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  2.064000e+04  2.064000e+04  2.064000e+04  2.064000e+04  2.064000e+04   
mean   5.508083e-18  5.508083e-18  1.290957e-18 -1.420053e-18 -3.442552e-19   
std    1.310204e-01  2.467756e-01  1.753950e-02  1.404874e-02  3.174030e-02   
min   -2.324638e-01 -5.419507e-01 -3.248795e-02 -2.262871e-02 -3.986874e-02   
25%   -9.015538e-02 -2.086174e-01 -7.005976e-03 -2.685655e-03 -1.789503e-02   
50%   -2.316320e-02  7.068893e-03 -1.416892e-03 -1.419802e-03 -7.272534e-03   
75%    6.017703e-02  1.639316e-01  4.419171e-03  8.451334e-05  8.394945e-03   
max    7.675362e-01  4.580493e-01  9.675120e-01  9.773713e-01  9.601313e-01   

           AveOccup      Latitude     Longitude  
count  2.064000e+04  2.064000e+04  2.064000e+04  
mean   5.378988e-21 -2.368476e-16 -1.707506e-15  
std    8.358045e-03  2.269875e-01  1.995550e-01  
min   -1.913946e-03 -3.285719e-01 -4.761251e-01  
25%   -5.157676e-04 -1.808567e-01 -2.221410e-01  
50%   -2.032280e-04 -1.457876e-01  1.075403e-01  
75%    1.702871e-04  2.208436e-01  1.553490e-01  
max    9.980861e-01  6.714281e-01  5.238749e-01

In [11]:
data = X
no_data = np.shape(data)[0]
no_data

20640

In [12]:
no_feature = np.shape(data)[1]
no_feature

8

In [13]:
#Function to compute correlation between two variables
#method:
# 1 = Feature Similarity: Correlation Coeff 
# 2 = Feature Similarity: Linear Regression error
# 3 = Feature Similarity: Maximal Information Compression Index
def f2f(x1,x2, method):
    no_x1=np.shape(x1)[0]
    no_x2=np.shape(x2)[0]
    dist=0.0
    if method == 1:
        pass
    if method == 2:
        pass
    if method == 3:
        sxy=0.0; sx=0.0; sy=0.0; mnx1=0.0; mnx2=0.0;
        for i in range(no_x1):
            sxy=sxy+x1[i]*x2[i]
            sx=sx+x1[i]**2
            sy=sy+x2[i]**2
            mnx1=mnx1+x1[i]
            mnx2=mnx2+x2[i]
        mnx1=mnx1/no_x1;
        mnx2=mnx2/no_x2;

        sxy=(sxy/no_x1)- mnx1*mnx2;
        sx=(sx/no_x1)-mnx1**2
        sy=(sy/no_x1)-mnx2**2

        if (sx-sy) ==0:
            theta=0.5*np.pi/2
        else:
            theta=0.5*np.arctan(2*sxy/(sx-sy))

        a = -1 / np.tan(theta)
        b = np.mean(x1)*(-a) - np.mean(x2)

        dist = 0.0
        for i in range(no_x1):
            dist=dist+abs((x2[i]-a*x1[i]-b) / np.sqrt(a**2 + b**2))
        dist = dist/no_x1
        return dist 

In [14]:
# Function to find the lowest error
def lowerror(dm,k):
    no_feature = np.shape(dm)[0]
    HIGH = 9999
    for i in range(no_feature):
        if dm[i,i] == 1:
            kd[i] = HIGH
        elif i ==1:
            dd = [HIGH, dm[0,1:]]
        elif i == no_feature:
            dd = np.con
            

In [15]:
# Function to recompute the distance matrix during clustering
import numpy as np

def updatedm(dm, indx, k):
    no_feature = dm.shape[0]
    HIGH = 9999
    i = indx

    if i == 0:
        dd = [HIGH] + list(dm[0, 1:])
        for l in range(no_feature):
            if dm[l, l] == 1:
                dd[l] = HIGH
    elif i == no_feature - 1:
        dd = list(dm[0:no_feature - 1, no_feature - 1]) + [HIGH]
        for l in range(no_feature):
            if dm[l, l] == 1:
                dd[l] = HIGH
    else:
        dd = list(dm[0:i, i]) + [HIGH] + list(dm[i, i + 1:no_feature])
        for l in range(no_feature):
            if dm[l, l] == 1:
                dd[l] = HIGH

    dindx = np.argsort(dd)
    dm1 = np.copy(dm)

    for l in range(k):
        indx1 = dindx[l]
        dm1[indx1, indx1] = 1

    return dm1

# Example usage:
# Replace 'dm', 'indx', and 'k' with your specific values
# dm_result = updatedm(dm, indx, k)

In [33]:
## fsfs
def fsfs(data,k, method=3, original_size = None):
    """
    Reduces a feature set using the method described in:P. Mitra, C. A. Murthy and S. K. Pal,
    Unsupervised Feature Selection using Feature Similarity, IEEE Transactions on Pattern Analysis and Machine Intelligence,
    Vol .24, No. 4, pp 301-312, April 2002. 


    # Args

    #     data: Data matrix containing the original feature set. Each column represents a feature. In this Matrix, all columns are input features (There is no target column).
    #     k: Scale parameter which decides the size of the reduced feature set. Approximately, k = original_size - size of the reduced feature set.
    #     method: 1: Lasso Regression, 2: Ridge Regression, 3: Elastic Net Regression.
    #     original_size: Number of features in the original data set. It seems it is a redundent input argument, becuse we can calculate the number of features just by counting the number of columns in data matrix.


    # Returns:
    
    #     redu : Reduced features. A vector containing the feature numbers of the original feature set which are retained in the reduced set.
    #     fwt : feature weights of the features in redu. 

    """
    
    if original_size == None:
        original_size = data.shape[1]
    no_feature=original_size;
    no_data=np.shape(data)[0]

    kk=[]
    while k > (no_feature-1):

        print('Give a smaller value of k\n')
        k=input('k=  ')


    # Form the inter-feature distance matrix (Upper Triangular)
    """
    for i=1:no_feature,
       fprintf(1,'Similarity Computed for Feature No. %d\n',i);
       for j=1:no_feature,
          x1=data(:,i);x2=data(:,j);
          if i < j
             dm(i,j)=f2f(x1,x2,method);
          else
             dm(i,j)=0.0;
          end
       end
    end
    """
    print('Computing Feature Similarities..\n')
    dm  = np.zeros((no_feature,no_feature))

    for i in range (no_feature):
        print(f'Similarity Computed for Feature No.{i}')
        for j in range (no_feature):
            x1=data[:,i]
            x2=data[:,j]

            if i < j:
                dm[i,j] = f2f(x1,x2, method)
            else:
                dm[i,j] = 0
    print('*********************************************')
    print(f"dm matrix is: \n",dm)
    print('*********************************************')
    drift = 1.0

    # Form a vector containing the distance of k-NN for each feature.
    """  

    """
    print('Vectores containing the distance of k-NN for each feature')
    kd = np.empty(no_feature)
    for i in range (no_feature):
        if i==0:
            dd=dm[0,1:]
        elif i == no_feature - 1:
            dd = dm[:no_feature - 1, no_feature - 1].T
        else:
            dd = np.concatenate((dm[i, i + 1:], dm[:i, i].T))
        dd = sorted(dd)
        kd[i]  = dd[k-1] # --> Becuse of 0-indexed vectors in python, 
        print(f'dd for feature NO. {i}:')
        print(dd)
    print('**************************') 
    print("kd vector is: \n",kd)  

    kd0 = kd #--> Store the original r_k

    # Condense the feature set
    print('**************************') 
    print('Clustring the features...\n')
    rfs=[]; rfd=[]; ee=[];dmt=dm; lower=9999; iter=0; prev_lower=9999;
    tagm=np.ones(no_feature)
    while (no_feature - np.trace(dm)) > 0:
        iter = iter + 1
        if k > (no_feature - np.trace(dm) - 1):
            k = (no_feature - np.trace(dm) - 1)
        if k<= 0:
            break
        prev_lower = lower
        lower,fetr = lowerror(df,k)

        #Adjust k
        while lower > drift*prev_lower:
            k = k-1
            if k == 0:
                break
            lower, fetr = lowerror(df,k)


        if k <= 0:
            break
        dm = updatedm(dm,fetr,k) # --> need to be implemented 


        # kk=[kk;k];
        # ee=[ee;lower];
        kk.append(k)
        ee.append(lower)

        tagm[fetr]=0
        # for i=1:no_feature,
        #     for j=1:no_feature,
        #         if dm(i,i)==1
        #             tagm(i)=0;
        #         end
        #     end
        # end
        for i in range(no_feature):
            for j in range(no_feature):
                if dm[i,i] == 1: # -------------> shouldm't it be dm[i,j]??????? 
                    tagm[i] = 0
    
    # for i=1:no_feature,
    #     if dm(i,i)==0
    #         rfs=[rfs;i];
    #         rfd=[rfd;kd0(i)];
    #     end
    # end
    for i in range(no_feature):
        if dm[i,i] == 0:
            rfs.append(i)
            rfd.append(kd0[i])

    print('Features Clustered.\n')
    redu=rfs
    fwt=rfd

    return redu, fwt



In [34]:
tmp = fsfs(X, 3, method=3)

Computing Feature Similarities..

Similarity Computed for Feature No.0
Similarity Computed for Feature No.1
Similarity Computed for Feature No.2
Similarity Computed for Feature No.3
Similarity Computed for Feature No.4
Similarity Computed for Feature No.5
Similarity Computed for Feature No.6
Similarity Computed for Feature No.7
*********************************************
dm matrix is: 
 [[0.         0.09562147 0.09686892 0.09666673 0.09666232 0.09666178 0.09625775 0.09665185]
 [0.         0.         0.20691898 0.20689741 0.20719202 0.20689297 0.20648989 0.21125351]
 [0.         0.         0.         0.0093121  0.00799574 0.00792298 0.00791803 0.00790729]
 [0.         0.         0.         0.         0.00353262 0.00338224 0.00345044 0.00338494]
 [0.         0.         0.         0.         0.         0.02002329 0.01985276 0.01989137]
 [0.         0.         0.         0.         0.         0.         0.00060583 0.00059879]
 [0.         0.         0.         0.         0.         0.   

KeyError: (0, 0)

In [ ]:
np.ones(no_feature)

array([1., 1., 1., 1., 1., 1., 1., 1.])